#
# Makefile to clean the testing directory - deletes all test output files except for results.ps
#
# Last Revised: 17 Sep 2019 (SYZ) - Initial.
#

clean:
	@rm -f ?dump_???
	@rm -f ccoev cdump???avg_???
	@rm -f gem????_???
	@rm -f plot_???.ps cluster_example.ps trajfreq.ps
	@rm -f ccrop_??? HYSPLIT_???.kmz
	@rm -f stat_???.txt
	@rm -f CONC.040 MESSAGE.040 VMSDIST.040 WARNING.040
	@rm -f ERROR_LOG.txt WARNING message.txt
